filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 1
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        tests: true