version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: ishetkutweer-prod-mariadb
      working_dir: /var/www/ishetkutweer
      environment:
        - MYSQL_ROOT_PASSWORD=ishetkutweer
        - MYSQL_DATABASE=ishetkutweerv4
        - MYSQL_USER=ishetkutweer
        - MYSQL_PASSWORD=ishetkutweer
      ports:
        - "9003:3306"

    webserver:
      image: nginx:1.18.0-alpine
      container_name: ishetkutweer-prod-webserver
      working_dir: /var/www/ishetkutweer
      volumes:
        - datavolume:/var/www/ishetkutweer
        - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      image: tetterpon/ishetkutweer:latest
      container_name: ishetkutweer-prod-php-fpm
      working_dir: /var/www/ishetkutweer
      volumes:
        - datavolume:/var/www/ishetkutweer
        - ./docker/production/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

volumes:
  datavolume: {}
