version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: ishetkutweer-dev-mariadb
      volumes:
        - ./docker/development/mariadb/test-database.sql:/docker-entrypoint-initdb.d/01-test-database.sql
      environment:
        - MYSQL_ROOT_PASSWORD=ishetkutweer
        - MYSQL_DATABASE=ishetkutweerv4
        - MYSQL_USER=ishetkutweer
        - MYSQL_PASSWORD=ishetkutweer
      ports:
        - "9003:3306"

    nginx:
      build: docker/development/nginx
      container_name: ishetkutweer-dev-nginx
      working_dir: /var/www/ishetkutweer
      volumes:
          - ./public:/var/www/ishetkutweer/public
          - ./docker/development/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: docker/development/php-fpm
      container_name: ishetkutweer-dev-php-fpm
      working_dir: /var/www/ishetkutweer
      volumes:
        - .:/var/www/ishetkutweer
        - ./docker/development/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
