version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: ishetkutweer-prod-mariadb
      working_dir: /var/www/ishetkutweer
      environment:
        - MYSQL_ROOT_PASSWORD=ishetkutweer
        - MYSQL_DATABASE=ishetkutweerv4
        - MYSQL_USER=ishetkutweer
        - MYSQL_PASSWORD=ishetkutweer
      ports:
        - "9003:3306"

    nginx:
      image: repo.treescale.com/tetterpon/ishetkutweer-nginx:latest
      container_name: ishetkutweer-prod-nginx
      working_dir: /var/www/ishetkutweer
      volumes:
        - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      image: repo.treescale.com/tetterpon/ishetkutweer-php-fpm:latest
      container_name: ishetkutweer-prod-php-fpm
      working_dir: /var/www/ishetkutweer
      volumes:
        - ./docker/production/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
