weather_by_ip:
    path: /
    controller: App\Infrastructure\Controller\WeatherByIpController::getWeatherByIp

weather_by_location:
    path: /{location}
    controller: App\Infrastructure\Controller\WeatherByLocationController::getWeatherByLocation
