weather_by_ip:
    path: /
    controller: App\Infrastructure\Controller\Web\WeatherByIpController::getWeatherByIp
    methods: GET

weather_by_city:
    path: /{city}
    controller: App\Infrastructure\Controller\Web\WeatherByCityController::getWeatherByCity
    methods: GET

regions:
    path: /api/cities
    controller: App\Infrastructure\Controller\Api\CitiesController::getCities
    methods: GET
